name: CI devops 2025

on:
  # Cette CI se déclenche à chaque push sur main ou develop
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend: 
    # Exécute le job sur une machine Ubuntu 24.04
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : récupérer le code source du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : configurer le JDK 21 pour Maven/Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : compiler et tester le backend avec Maven
      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify
